spring:
  main:
    allow-circular-references: true
  
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  sql:
    init:
      mode: never
      # schema-locations: classpath:schema.sql
      # data-locations: classpath:data.sql  # 注释掉，因为项目中没有data.sql文件

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  expiration: 86400
  secret: your-very-long-and-secure-secret-key-that-should-be-at-least-32-characters

server:
  port: 8080

logging:
  level:
    com.blog.config.JwtAuthTokenFilter: DEBUG