spring:
  main:
    allow-circular-references: true
  
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  sql:
    init:
      mode: embedded
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: mySuperSecretKeyForJWTThatIsLongEnoughToBeSecure1234567890
  expiration: 86400

server:
  port: 8080

logging:
  level:
    com.blog.config.JwtAuthTokenFilter: